trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: fraud-detection
- name: buildConfiguration
  value: 'Release'

steps:
- script: 'net use C: \\filesharepublic.file.core.windows.net\data /u:filesharepublic $(filestorage.key)'
  displayName: 'Map disk drive to Azure Files share folder'
  
- script: dotnet build src/machine-learning/FraudPredictionTrainer/FraudPredictionTrainer.csproj --configuration $(buildConfiguration)
  displayName: 'Build Trainer Console App (dotnet build) $(buildConfiguration)'

- script: dotnet run --project src/machine-learning/FraudPredictionTrainer/FraudPredictionTrainer.csproj --configuration $(buildConfiguration)
  displayName: 'Train ML model (dotnet run)'